<a href="https://colab.research.google.com/github/NitinKarthik01/AIML_MSIS/blob/main/pandas_activity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Activity 1 : create dataset

import pandas as pd

data = {"Name":["Nitin","Swetha","Karthik"],
        "Age": [23,22,23],
        "Marks":[89,100,98]
}

df = pd.DataFrame(data)
print(df)

      Name  Age  Marks
0    Nitin   23     89
1   Swetha   22    100
2  Karthik   23     98

In [ ]:
#Activity 2

from sklearn.datasets import load_diabetes

diabetes = load_diabetes(as_frame=True)
df=diabetes.frame
df.head()

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

In [ ]:
# Activity 3

df.info()
df.describe()
df.tail()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 442 entries, 0 to 441
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   age     442 non-null    float64
 1   sex     442 non-null    float64
 2   bmi     442 non-null    float64
 3   bp      442 non-null    float64
 4   s1      442 non-null    float64
 5   s2      442 non-null    float64
 6   s3      442 non-null    float64
 7   s4      442 non-null    float64
 8   s5      442 non-null    float64
 9   s6      442 non-null    float64
 10  target  442 non-null    float64
dtypes: float64(11)
memory usage: 38.1 KB

(442, 11)

In [ ]:
#Activity 4 : Selecting Data

df[['age','target']]

# df.iloc[:8]
df.loc[10:20]

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
10,-0.096328,-0.044642,-0.083808,0.008101,-0.103389,-0.090561,-0.013948,-0.076395,-0.062917,-0.034215,101.0
11,0.027178,0.050680,0.017506,-0.033213,-0.007073,0.045972,-0.065491,0.071210,-0.096435,-0.059067,69.0
12,0.016281,-0.044642,-0.028840,-0.009113,-0.004321,-0.009769,0.044958,-0.039493,-0.030748,-0.042499,179.0
13,0.005383,0.050680,-0.001895,0.008101,-0.004321,-0.015719,-0.002903,-0.002592,0.038394,-0.013504,185.0
14,0.045341,-0.044642,-0.025607,-0.012556,0.017694,-0.000061,0.081775,-0.039493,-0.031988,-0.075636,118.0
15,-0.052738,0.050680,-0.018062,0.080401,0.089244,0.107662,-0.039719,0.108111,0.036060,-0.042499,171.0
16,-0.005515,-0.044642,0.042296,0.049415,0.024574,-0.023861,0.074412,-0.039493,0.052277,0.027917,166.0
17,0.070769,0.050680,0.012117,0.056301,0.034206,0.049416,-0.039719,0.034309,0.027364,-0.001078,144.0
18,-0.038207,-0.044642,-0.010517,-0.036656,-0.037344,-0.019476,-0.028674,-0.002592,-0.018114,-0.017646,97.0
19,-0.027310,-0.044642,-0.018062,-0.040099,-0.002945,-0.011335,0.037595,-0.039493,-0.008943,-0.054925,168.0
20,-0.049105,-0.044642,-0.056863,-0.043542,-0.045599,-0.043276,0.000779,-0.039493,-0.011897,0.015491,68.0

In [ ]:
#Activity 5 : Filtering

df[df['target']==69]

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
11,0.027178,0.050680,0.017506,-0.033213,-0.007073,0.045972,-0.065491,0.071210,-0.096435,-0.059067,69.0
384,0.034443,0.050680,-0.029918,0.004658,0.093372,0.086994,0.033914,-0.002592,0.024055,-0.038357,69.0
393,-0.074533,-0.044642,-0.046085,-0.043542,-0.029088,-0.023234,0.015505,-0.039493,-0.039809,-0.021788,69.0

In [ ]:
#Activity 6 : Sorting
df.sort_values(by='age')

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,target
26,-0.107226,-0.044642,-0.077342,-0.026328,-0.089630,-0.096198,0.026550,-0.076395,-0.042571,-0.005220,137.0
374,-0.107226,-0.044642,-0.034229,-0.067642,-0.063487,-0.070520,0.008142,-0.039493,-0.000612,-0.079778,140.0
344,-0.107226,-0.044642,-0.011595,-0.040099,0.049341,0.064447,-0.013948,0.034309,0.007027,-0.030072,200.0
242,-0.103593,0.050680,-0.023451,-0.022885,-0.086878,-0.067701,-0.017629,-0.039493,-0.078140,-0.071494,71.0
226,-0.103593,0.050680,-0.046085,-0.026328,-0.024960,-0.024800,0.030232,-0.039493,-0.039809,-0.054925,77.0
...,...,...,...,...,...,...,...,...,...,...,...
211,0.092564,-0.044642,0.036907,0.021872,-0.024960,-0.016658,0.000779,-0.039493,-0.022517,-0.021788,70.0
311,0.096197,-0.044642,0.040140,-0.057313,0.045213,0.060690,-0.021311,0.036154,0.012551,0.023775,180.0
321,0.096197,-0.044642,0.051996,0.079265,0.054845,0.036577,-0.076536,0.141322,0.098648,0.061054,230.0
204,0.110727,0.050680,0.006728,0.028758,-0.027712,-0.007264,-0.047082,0.034309,0.002004,0.077622,277.0
402,0.110727,0.050680,-0.033151,-0.022885,-0.004321,0.020293,-0.061809,0.071210,0.015568,0.044485,168.0

In [ ]:
#Assignment

# total no.of passengers
# find avg age of survivers and non survivers
#list the passengers who are older thann 60 years
#find the avg fare of each passenger class

file_path = r"/content/drive/MyDrive/titanic.csv"
df = pd.read_csv(file_path)
df.head()

print("The no.of Passengers on Titanic are",len(df))
print(" ")
print("The average age of Survivers",df.loc[df['Survived'] == 1, 'Age'].mean() )
print(" ")
print("The average age of Non - Survivers",df.loc[df['Survived'] == 0, 'Age'].mean() )
print(" ")
print("The average fare of CLASS 1 ",df.loc[df['Pclass'] == 1, 'Fare'].mean() )
print(" ")
print("The average fare of CLASS 2 ",df.loc[df['Pclass'] == 2, 'Fare'].mean() )
print(" ")
print("The average fare of CLASS 3 ",df.loc[df['Pclass'] == 3, 'Fare'].mean() )
print(" ")
x = df[df['Age'] > 60]
print("The lis of passengers above 60 \n",x)

The no.of Passengers on Titanic are 887

The average age of Survivers 28.408391812865496

The average age of Non - Survivers 30.13853211009174

The average fare of CLASS 1  84.1546875

The average fare of CLASS 2  20.662183152173913

The average fare of CLASS 3  13.707707392197124

The lis of passengers above 60
      Survived  Pclass                                      Name     Sex   Age  \
33          0       2                      Mr. Edward H Wheadon    male  66.0
53          0       1             Mr. Engelhart Cornelius Ostby    male  65.0
63          0       1                      Mr. Albert A Stewart    male  64.0
95          0       1                  Mr. George B Goldschmidt    male  71.0
115         0       3                       Mr. Patrick Connors    male  70.5
169         0       1                  Mr. Wyckoff Van der hoef    male  61.0
251         0       1                  Mr. William Thomas Stead    male  62.0
273         1       1          Miss. Kornelia Theodosia Andrews  female  63.0
278         0       3                           Mr. Frank Duane    male  65.0
324         0       3                  Mr. Johan Hansen Nysveen    male  61.0
435         0       1                          Mr. Mark Fortune    male  64.0
453         0       1                  Mr. Francis Davis Millet    male  65.0
480         1       3                     Mrs. (Hedwig) Turkula  female  63.0
490         0       1                    Mr. Ramon Artagaveytia    male  71.0
508         0       3                          Mr. James Webber    male  66.0
535         0       3                   Mr. Samuel Beard Risien    male  69.0
542         0       1               Mr. Arthur Ernest Nicholson    male  64.0
552         0       1                         Mr. George Wright    male  62.0
561         0       3             Miss. (Marion Ogden) Meanwell  female  62.0
567         1       2                         Mr. George Harris    male  62.0
622         0       1                      Mr. Frederick Sutton    male  61.0
627         1       1       Mr. Algernon Henry Wilson Barkworth    male  80.0
669         0       2                Mr. Henry Michael Mitchell    male  70.0
741         0       1               Capt. Edward Gifford Crosby    male  70.0
825         1       1  Mrs. George Nelson (Martha Evelyn) Stone  female  62.0
847         0       3                        Mr. Johan Svensson    male  74.0

     Siblings/Spouses Aboard  Parents/Children Aboard      Fare
33                         0                        0   10.5000
53                         0                        1   61.9792
63                         0                        0   27.7208
95                         0                        0   34.6542
115                        0                        0    7.7500
169                        0                        0   33.5000
251                        0                        0   26.5500
273                        1                        0   77.9583
278                        0                        0    7.7500
324                        0                        0    6.2375
435                        1                        4  263.0000
453                        0                        0   26.5500
480                        0                        0    9.5875
490                        0                        0   49.5042
508                        0                        0    8.0500
535                        0                        0   14.5000
542                        0                        0   26.0000
552                        0                        0   26.5500
561                        0                        0    8.0500
567                        0                        0   10.5000
622                        0                        0   32.3208
627                        0                        0   30.0000
669                        0                        0   10.5000
741                        1                        1   71.0000
825                        0                        0   80.0000
847                        0                        0    7.7750